### ISSUE TITLE
BOT api not honoring the pairs all the time

### ISSUE THREAD

**Issue by eli007s** [3commas-io/3commas-official-api-docs#66] opened 2021-06-23 11:10 UTC
I'm using the update bot api and over several tests the api seems to take a compound pair such as 

```
pairs: [
    'USD_ADA',  'USD_ALGO', 'USD_ATOM',  'USD_BAND',
    'USD_BAT',  'USD_BCH',  'USD_BNB',   'USD_BTC',
    'USD_BUSD', 'USD_DAI',  'USD_DASH',  'USD_DOGE',
    'USD_EGLD', 'USD_ENJ',  'USD_EOS',   'USD_ETC',
    'USD_ETH',  'USD_FIL',  'USD_HBAR',  'USD_HNT',
    'USD_ICX',  'USD_IOTA', 'USD_LTC',   'USD_MANA',
    'USD_MKR',  'USD_NANO', 'USD_NEO',   'USD_OMG',
    'USD_ONE',  'USD_ONT',  'USD_OXT',   'USD_QTUM',
    'USD_REP',  'USD_RVN',  'USD_SOL',   'USD_USDC',
    'USD_VET',  'USD_VTHO', 'USD_WAVES', 'USD_XLM',
    'USD_XTZ',  'USD_ZEC',  'USD_ZEN',   'USD_ZIL',
    'USD_ZRX'
  ]
```

and after some time the bot will be updated with

```
pairs: [ 'USDT_ZRX' ],
```

no matter what voodoo i try with the update call, it will always resort to using the last pair in the list.

you can see my code that I'm using at: [https://github.com/eli007s/3commas-compounding/blob/main/index.js#L74](https://github.com/eli007s/3commas-compounding/blob/main/index.js#L74)

**Comment by EfremovEvgeniy** [comment] 2021-07-02 08:59
Hi, I can't reproduce it. Does this happen with all your bots or only with a specific?

**Comment by 3commas-io** [comment] 2021-07-08 08:51
Please provide at least bot_id so we could review this. Until that i close this issue, feel free to reopen it if problem persists

**Closed by 3commas-io** 2021-07-08 08:51 UTC

**Comment by f3lix3rown** [comment] 2021-10-09 16:38
I am having the same issue. It only enters the last pair from my pair array. The bot ID is 6322211.

**Comment by walidbahgat** [comment] 2021-11-14 00:03
could someone tell me, how this issue is resolved as i'm facing this issue
