### ISSUE TITLE
Grid strange behavior

### ISSUE THREAD

**Issue by cj4c0b1** [3commas-io/3commas-official-api-docs#23] opened 2020-11-30 14:43 UTC
Hi guys at 3commas team
I just noted this behavior in some of my Grid bots.
![image](https://user-images.githubusercontent.com/22513754/100623285-3c63a500-3322-11eb-95eb-0f37676f5986.png)
as you can see there is scrambled orders, buy and sell mixed on what i can observe as a wrong lines.
Is this a problem with the grid algorithm ?
Is there a limit for the number of lines stored in the Grid structure ? - I noted that all lines are stored, even the canceled ones and as I'm running the same Grid for long time it should has tons of lines. Is this a problem ? is there a solution or a workaround to fix it ?

The way I'm solving this for now is to edit and restart the bot.

thanks!

**Comment by cj4c0b1** [comment] 2020-11-30 19:26
just got it again on another grid
![image](https://user-images.githubusercontent.com/22513754/100654533-400b2200-334a-11eb-8925-8389f913bf6e.png)

**Comment by cj4c0b1** [comment] 2020-12-05 16:28
Well, I'm creating an grid lines auditor to fix that in the mean time.

**Comment by sadgb** [comment] 2020-12-29 11:14
So the problem is that gridbot was unable to place an order for some reason. Most likely it was "not enough funds"

But the only place where you could check those messages right now is telegram bot notifications. Which is not good at all

So we will change how widget display lines with errors and add the place to check grid bot logs

**Comment by cj4c0b1** [comment] 2020-12-30 11:21
Thanks by the update!
I will check if this is the case condition but seems to be logical!

**Comment by 3commas-io** [comment] 2021-02-25 15:32
Since this is smth not related to API i will close this

**Closed by 3commas-io** 2021-02-25 15:32 UTC
